# Generated by Django 3.2 on 2021-05-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_avialable',
            field=models.BooleanField(default=True),
        ),
    ]
