# Generated by Django 3.2 on 2021-05-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0002_dish_is_avialable'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='calories',
            field=models.IntegerField(null=True),
        ),
    ]
