# Generated by Django 3.2 on 2021-05-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0003_dish_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='calories',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
