# Generated by Django 3.2 on 2021-05-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0004_alter_dish_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='calories',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
