# Generated by Django 3.2 on 2021-05-07 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0006_alter_dish_calories'),
        ('order', '0002_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addition_dish', to='dish.dish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addition_dish', to='order.order')),
            ],
            options={
                'verbose_name': 'Доп. блюдо',
                'verbose_name_plural': 'Доп. блюда',
            },
        ),
    ]
