# Generated by Django 3.2.2 on 2021-07-04 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_restaurant'),
        ('order', '0005_order_user'),
    ]

    operations = [
    ]
